export enum CustodyEventType {
  OWNER_HANDOFF = 'OWNER_HANDOFF',
  PLATFORM_INTAKE = 'PLATFORM_INTAKE',
  CONDITION_CHECK = 'CONDITION_CHECK',
  RENTER_DELIVERY = 'RENTER_DELIVERY',
  RENTER_RETURN = 'RENTER_RETURN',
  PLATFORM_INSPECTION = 'PLATFORM_INSPECTION',
  OWNER_RETURN = 'OWNER_RETURN',
}
