export type DomainErrorCode =
  | 'INVALID_OWNER'
  | 'INVALID_VALUATION'
  | 'INVALID_EMAIL'
  | 'INVALID_NAME'
  | 'INVALID_RENTAL_DATES'
  | 'INVALID_RENTAL_PARTIES'
  | 'UNAUTHORIZED'
  | 'WATCH_UNAVAILABLE'
  | 'INVALID_STATE_TRANSITION'
  | 'VERSION_CONFLICT'
  | 'DUPLICATE_REQUEST'
  | 'WATCH_ALREADY_RESERVED'
  | 'TOKEN_EXPIRED'
  | 'INVALID_CREDENTIALS'
  | 'TOO_MANY_ATTEMPTS'
  | 'INVALID_ESCROW_TRANSITION'
  | 'INVALID_PAYMENT_TRANSITION'
  | 'INVALID_LEDGER_IMBALANCE'
  | 'INVALID_LEDGER_TRANSITION'
  | 'INSUFFICIENT_LEDGER_BALANCE'
  | 'RISK_POLICY_VIOLATION'
  | 'HIGH_RISK_TRANSACTION'
  | 'SUSPICIOUS_VELOCITY'
  | 'COLLUSION_RISK'
  | 'ANOMALOUS_TRANSACTION'
  | 'CUSTODY_VIOLATION'
  | 'KYC_REQUIRED'
  | 'CITY_NOT_ACTIVE'
  | 'WATCH_NOT_VERIFIED'
  | 'CONDITION_REPORT_INVALID'
  | 'CUSTODY_EVIDENCE_REQUIRED'
  | 'INSURANCE_POLICY_INVALID'
  | 'DISPUTE_LOCK'
  | 'REVIEW_REQUIRED'
  | 'ECONOMICS_NEGATIVE'
  | 'PLATFORM_EXPOSURE_LIMIT'
  | 'RISK_EXCEEDS_CAP'
  | 'PLATFORM_EXPOSURE_VIOLATION'
  | 'TIER_ACCESS_DENIED'
  | 'INVENTORY_BELOW_MINIMUM'
  | 'INSURANCE_INACTIVE'
  | 'RETURN_NOT_CONFIRMED';

const DOMAIN_ERROR_CODES: ReadonlySet<string> = new Set([
  'INVALID_OWNER',
  'INVALID_VALUATION',
  'INVALID_EMAIL',
  'INVALID_NAME',
  'INVALID_RENTAL_DATES',
  'INVALID_RENTAL_PARTIES',
  'UNAUTHORIZED',
  'WATCH_UNAVAILABLE',
  'INVALID_STATE_TRANSITION',
  'VERSION_CONFLICT',
  'DUPLICATE_REQUEST',
  'WATCH_ALREADY_RESERVED',
  'TOKEN_EXPIRED',
  'INVALID_CREDENTIALS',
  'TOO_MANY_ATTEMPTS',
  'INVALID_ESCROW_TRANSITION',
  'INVALID_PAYMENT_TRANSITION',
  'INVALID_LEDGER_IMBALANCE',
  'INVALID_LEDGER_TRANSITION',
  'INSUFFICIENT_LEDGER_BALANCE',
  'RISK_POLICY_VIOLATION',
  'HIGH_RISK_TRANSACTION',
  'SUSPICIOUS_VELOCITY',
  'COLLUSION_RISK',
  'ANOMALOUS_TRANSACTION',
  'CUSTODY_VIOLATION',
  'KYC_REQUIRED',
  'CITY_NOT_ACTIVE',
  'WATCH_NOT_VERIFIED',
  'CONDITION_REPORT_INVALID',
  'CUSTODY_EVIDENCE_REQUIRED',
  'INSURANCE_POLICY_INVALID',
  'DISPUTE_LOCK',
  'REVIEW_REQUIRED',
  'ECONOMICS_NEGATIVE',
  'PLATFORM_EXPOSURE_LIMIT',
  'RISK_EXCEEDS_CAP',
  'PLATFORM_EXPOSURE_VIOLATION',
  'TIER_ACCESS_DENIED',
  'INVENTORY_BELOW_MINIMUM',
  'INSURANCE_INACTIVE',
  'RETURN_NOT_CONFIRMED',
]);

export function isDomainErrorCode(value: string): value is DomainErrorCode {
  return DOMAIN_ERROR_CODES.has(value);
}
